from bp_cupid.models.Landkreis import Landkreis
from bp_cupid.models.Verwaltungszeitraum import Verwaltungszeitraum
from bp_cupid.models.Student import Student
from bp_cupid.models.Block import Block
from bp_cupid.models.Zeitraum import Zeitraum
from bp_cupid.models.Praxis import Praxis
from bp_cupid.models.Platzbegrenzung import Platzbegrenzung
from bp_cupid.models.Gewicht import Gewicht
from bp_cupid.models.Platz import Platz
from bp_cupid.models.Mitarbeiter import Mitarbeiter
from bp_cupid.models.Vorlage import Vorlage
from bp_cupid.models.ZusatzinfoPraxis import ZusatzinfoPraxis
from .Evaluation import Evaluation
